name: Test Pull

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Pull Brix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Brix
        uses: brix-os/brix-action@v1
        with:
          pullAfterInstall: false

      - name: Test Brix
        run: which brix
          
      - name: Describe Brix
        run: |
          /var/guix/profiles/per-user/root/current-guix/bin/guix describe

      - name: Configure Brix + Nonguix channels
        run: |
          mkdir -p ~/.config/guix
          cat > ~/.config/guix/channels.scm <<'EOF'
          (cons*
            (channel
              (name 'nonguix)
              (url "https://gitlab.com/nonguix/nonguix")
              (introduction
                (make-channel-introduction
                  "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
                  (openpgp-fingerprint
                    "2A39 3FFF 68F4 EF7A 3D29 12AF 6F51 20A0 22FB B2D5"))))
            (channel
              (name 'guix)
              (url "https://github.com/brix-os/brix.git")
              (branch "ci-testing"))
            %default-channels)
          EOF

      - name: Pull
        run: /var/guix/profiles/per-user/root/current-guix/bin/guix pull --allow-downgrades --disable-authentication -M 6 -K -v 3
        
